title: SYNTAX TERROR
title-hover: SYNT4X T3RR0R
description: Coding, rants and undefined behaviour
tags: software-engineering, coding, rants
template: light
post-preview-count: 5
post-preview-length: 100
contact: https://github.com/synterror/synterror
home: https://synterror.github.io/
folders:
  site: ..
