title: SYNTAX TERROR
title-hover: SYNT4X T3RR0R
description: Coding, rants and undefined behaviour
tags:
  - software-engineering
  - coding
  - rants
template: light
post-preview-count: 5
post-preview-length: 400
contact: https://github.com/synterror/synterror.github.io
home: https://synterror.github.io/
folders:
  site: ..
  posts: ../sources
